version: "3.8"
services:
  app:
    image: ferpa708/test:latest
    ports:
      - 3008:3008
    volumes:
      - ${APP_DATA_DIR}/data:/app
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      NODE_ENV: production
      REDIS_URI: redis://cache:6379
      MODULE_NAME: urlx
      DEBUG: ndk:*,urlx:*
      PORT: 3008
      NOSTR_PRIVATE_KEY: 1b0e0c73b4fbf4e74c2337279fd371db09309fe00aa06695d3ff728972d39664
      NOSTR_PUBLIC_KEY: f57d0e93625495b568a2dbb30a7fd6a29e836d92b8ba4f0cef6cf12353b3ba43
      NOSTR_RELAYS: wss://relay.damus.io,wss://relay.hodl.ar,wss://nostr.wine,wss://offchain.pub,wss://nostr-pub.wellorder.net,wss://nos.lol
      LEDGER_PUBLIC_KEY: c585d68572463bbdfd0147441a363061bd85a14175695ffd8dbd03a33b57c45a
      NOSTR_WRITE_RELAY: wss://relay.damus.io
      LND_HOST: $APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT/
      LND_CERT: /lnd/tls.cert
      LND_MACAROON: /lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon
      ACCEPTED_BASE_FEE: 2000
      ACCEPTED_FEE_PERCENT: 0.003
    depends_on:
      - cache
    networks:
      - umbrel_default
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data
    networks:
      - umbrel_default
volumes:
  cache:
    driver: local
networks:
  umbrel_default:
    external: true
