version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: development-lawallet_web_1
      APP_PORT: 3009
      PROXY_AUTH_ADD: "false"

  web:
    image: ferpa708/test:latest
    volumes:
      - "${APP_DATA_DIR}/data:/data"
      - "${APP_LIGHTNING_NODE_DATA_DIR}:/data/.lnd"
    environment:
      NODE_ENV: "production"
      REDIS_URI: "redis://cache:6379"
      MODULE_NAME: "urlx"
      DEBUG: "ndk:*,urlx:*"
      PORT: 3009
      NOSTR_PRIVATE_KEY: "1b0e0c73b4fbf4e74c2337279fd371db09309fe00aa06695d3ff728972d39664"
      NOSTR_PUBLIC_KEY: "f57d0e93625495b568a2dbb30a7fd6a29e836d92b8ba4f0cef6cf12353b3ba43"
      NOSTR_RELAYS: "wss://relay.damus.io,wss://relay.hodl.ar,wss://nostr.wine,wss://offchain.pub,wss://nostr-pub.wellorder.net,wss://nos.lol"
      LEDGER_PUBLIC_KEY: "c585d68572463bbdfd0147441a363061bd85a14175695ffd8dbd03a33b57c45a"
      NOSTR_WRITE_RELAY: "wss://relay.damus.io"
      LND_HOST: "${APP_LIGHTNING_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      LND_CERT: "/data/.lnd/tls.cert"
      LND_MACAROON: "/data/.lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/admin.macaroon"
      ACCEPTED_BASE_FEE: 2000
      ACCEPTED_FEE_PERCENT: 0.003
    depends_on:
      - cache
    networks:
      - umbrel_default

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data
    networks:
      - umbrel_default
volumes:
  cache:
    driver: local
networks:
  umbrel_default:
    external: true
