#!/bin/bash

ENV_FILE="${APP_DATA_DIR}/development-urlx/data/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Generating .env file..."

    NOSTR_PRIVATE_KEY=$(openssl rand -hex 32)
    NOSTR_PUBLIC_KEY=$(echo -n "$NOSTR_PRIVATE_KEY" | sha256sum | awk '{print $1}')

    cat <<EOF > "$ENV_FILE"
NOSTR_PRIVATE_KEY=$NOSTR_PRIVATE_KEY
NOSTR_PUBLIC_KEY=$NOSTR_PUBLIC_KEY
EOF

    echo ".env file generated at: $ENV_FILE"
else
    echo ".env file already exists. Skipping key generation."
fi

echo "Generated .env content:"
cat "$ENV_FILE"

exit 0