version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: development-front_web_1
      APP_PORT: 8001
      PROXY_AUTH_ADD: "false"

  web:
    image: ferpa708/web:latest
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NODE_ENV: "production"
      PORT: 8001
      LEDGER_PUBLIC_KEY: "${LAWALLET_LEDGER_PUBLIC_KEY}"
      URLX_PUBLIC_KEY: "${LAWALLET_MINTER_PUBLIC_KEY}"
      NOSTR_RELAYS: "ws://nostr-relay_app_proxy_1:4848"
      API_ENDPOINT: "http://development-urlx_web_1:3009"
      FEDERATION_ID: "test"
