version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: development-urlx_web_1
      APP_PORT: 3009
      PROXY_AUTH_ADD: "false"

  web:
    image: ferpa708/test:latest
    user: root
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/app/lnd:ro
    environment:
      NODE_ENV: "production"
      REDIS_URI: "redis://cache:6379"
      MODULE_NAME: "urlx"
      DEBUG: "ndk:*,urlx:*"
      PORT: 3009
      NOSTR_RELAYS: "wss://relay.damus.io,wss://relay.hodl.ar,wss://nostr.wine,wss://offchain.pub,wss://nostr-pub.wellorder.net,wss://nos.lol"
      LEDGER_PUBLIC_KEY: "c585d68572463bbdfd0147441a363061bd85a14175695ffd8dbd03a33b57c45a"
      NOSTR_WRITE_RELAY: "wss://relay.damus.io"
      LND_HOST: "${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_GRPC_PORT}"
      LND_CERT: "/app/lnd/tls.cert"
      LND_MACAROON: "/app/lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/admin.macaroon"
      ACCEPTED_BASE_FEE: 2000
      ACCEPTED_FEE_PERCENT: 0.003
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
