version: "3.8"
services:
  app_proxy:
    environment:
      APP_HOST: lawallet-lightning_app_1
      APP_PORT: 3009
      PROXY_AUTH_ADD: "false"

  app:
    image: ferpa708/urlx:latest
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/app/lnd:ro
    environment:
      NODE_ENV: "production"
      REDIS_URI: "redis://cache:6379"
      MODULE_NAME: "urlx"
      DEBUG: "ndk:*,urlx:*"
      PORT: 3009
      NOSTR_PRIVATE_KEY: "${LAWALLET_MINTER_PRIVATE_KEY}"
      NOSTR_PUBLIC_KEY: "${LAWALLET_MINTER_PUBLIC_KEY}"
      NOSTR_RELAYS: "ws://nostr-relay_app_proxy_1:4848"
      LEDGER_PUBLIC_KEY: "${LAWALLET_LEDGER_PUBLIC_KEY}"
      NOSTR_WRITE_RELAY: "ws://nostr-relay_app_proxy_1:4848"
      LND_HOST: "${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_GRPC_PORT}"
      LND_CERT: "/app/lnd/tls.cert"
      LND_MACAROON: "/app/lnd/data/chain/bitcoin/${APP_BITCOIN_NETWORK}/admin.macaroon"
      ACCEPTED_BASE_FEE: 2000
      ACCEPTED_FEE_PERCENT: 0.003
      BASE_URL: http://umbrel.local:8000
    restart: "on-failure"
    stop_grace_period: "1m"
    init: true
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data/redis

volumes:
  cache:
    driver: local
